apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-app
    app.kubernetes.io/component: vote-app
    app.kubernetes.io/instance: vote-app
  name: vote-app
spec:
  selector:
    matchLabels:
      deployment: vote-app
  template:
    metadata:
      labels:
        deployment: vote-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/acs-pipeline-demo/vote-app@sha256:19d971d81d3ec53029b94656c6de94b70d422afd88504eca9053fe6ac49907f0
        name: vote-app
        ports:
        - containerPort: 8080
          protocol: TCP
