apiVersion: v1
kind: BuildConfig
metadata:
  name: vote-app-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
          agent any
          stages {
            stage('Build') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject() {
                      openshift.startBuild("vote-app").logs('-f')
                    }
                  }
                }
              }
            }
            stage('Deploy') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject() {
                      dc = openshift.selector("dc", "vote-app")
                      dc.rollout().latest()
                      timeout(10) {
                          dc.rollout().status("-w")
                      }
                    }
                  }
                }
              }
            }
            stage('Test') {
              steps {
                sh "curl -v -X POST http://vote-app:8080/vote.html -d vote=1"
                sh "curl -v -X POST http://vote-app:8080/vote.html -d vote=1"
                sh "curl -v -X POST http://vote-app:8080/vote.html -d vote=1"
                sh "curl -v http://vote-app:8080/results.html| grep data:....3"
              }
            }
            stage('Promote to Prod') {
              steps {
                timeout(time:15, unit:'MINUTES') {
                    input message: "Approve Promotion to Prod?", ok: "Promote"
                }
                script {
                  openshift.withCluster() {
                    openshift.withProject() {
                      openshift.tag("vote-app:latest", "vote-app:prod") 
                    }
                  }
                }
              }
            }
          }
        }
    type: JenkinsPipeline
