apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:7072a7969a0dd5bccd517dd6da06c5f446820277e6429a398cf493ee55d09c9d
      namespace: vote-app-dev
    name: uat
    referencePolicy:
      type: Source
