apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:9cc18daf90876a3d86fd19f92c90a8f561fe949faca66ccbd5235ec455a95898
      namespace: vote-app-dev
    name: uat
    referencePolicy:
      type: Source
