apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:d4481c7cef0acb31e415fc648080a82e7ad387749a52126347fc81319293390b
      namespace: vote-app-dev
    name: uat
    referencePolicy:
      type: Source
