apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:30cdae6975bf5cae4e6e21bc6f00f9cb201f52a248586b5768cf8e564edd48ea
      namespace: vote-app-dev
    name: uat
    referencePolicy:
      type: Source
