apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:0facc13ea59f2c4f00c75bdebf8c31a43c19acfb6b11e2315b33cb2a987cc161
      namespace: vote-app-dev
    name: uat
    referencePolicy:
      type: Source
