apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:53187342e0acbf34c91b38765bdb8cf4180a19ba45fc2e56c4fcb2b8b1d8b31f
      namespace: vote-app-dev
    name: uat
    referencePolicy:
      type: Source
