apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:ea726ca0dc7b69785f9a6a7ec4c813a13c6d7ef9f3f73f450b7b14be8bddd6ef
      namespace: vote-app-dev
    name: uat
    referencePolicy:
      type: Source
