apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"vote-app:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"vote-app\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: vote-app
    app.kubernetes.io/component: vote-app
    app.kubernetes.io/instance: vote-app
  name: vote-app
  selfLink: /apis/apps/v1/namespaces/demo1/deployments/vote-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: vote-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: vote-app
    spec:
      containers:
      - env:
        - name: ENDPOINT_ADDRESS
          value: db
        - name: PORT
          value: "3306"
        - name: DB_NAME
          value: vote
        - name: MASTER_USERNAME
          value: user
        - name: MASTER_PASSWORD
          value: password
        - name: DB_TYPE
          value: mysql
        image: image-registry.openshift-image-registry.svc:5000/demo1/vote-app@sha256:685c51a96692f9c36d3d86e5b8c08fbfd1cfd26d4d12d59a991321748315032a
        imagePullPolicy: IfNotPresent
        name: vote-app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
