apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:e5f5f73d99aed0e1710a7e72f6a9dae9fea06cb20ea0bf9070e77d95ff381b43
      namespace: vote-app-dev 
    name: uat
    referencePolicy:
      type: Source
