apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:06108d07d1b59525e40812e9ce8f188b58217676be9bf6d2929aaf521dcb234a
      namespace: acs-pipeline-demo
    name: uat
    referencePolicy:
      type: Source
