apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:2b2df4caded78a41dae6f81a23526ca48907d9d3c6c21ed169604f40365e5262
      namespace: acs-pipeline-demo
    name: uat
    referencePolicy:
      type: Source
