apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:c036fd9a26a915aa67b73e70a80675a9979af0b5914f3ca23e19c6d84b193e85
      namespace: vote-app-dev
    name: uat
    referencePolicy:
      type: Source
