apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:ac110e05aa5dbeb18b875e25c929428fdc0fb8d155edc9e99dde37b76d9a655c
      namespace: acs-pipeline-demo
    name: uat
    referencePolicy:
      type: Source
