apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:92f981c2884582f2c37c5fcc9c058ecae0fcb62cb484df7ee5d3ba8939f6d1be
      namespace: acs-pipeline-demo
    name: uat
    referencePolicy:
      type: Source
