apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:9014ad1360879e6bf628c8272fc6ef23e131b5b16f407bd24e1cf03e55d331eb
      namespace: vote-app-dev
    name: uat
    referencePolicy:
      type: Source
