apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:8d3196c5356454f4e6440e2e6dac005e079a3d61418015d96ce3deec83343456
      namespace: acs-pipeline-demo
    name: uat
    referencePolicy:
      type: Source
