apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:92216de93251ca94e0b26a09e3824b3ba8c527f1599200ea7512adc93e46cb5b
      namespace: acs-pipeline-demo
    name: uat
    referencePolicy:
      type: Source
