apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:84a6e5c9ce3d02ed4093e03b158916b5cbe1401d3d6f13b35303d9e0952f9f4f
      namespace: vote-app-dev
    name: uat
    referencePolicy:
      type: Source
