apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-uat
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:d97c2b5bf63958799af41dcca1f47e4272c4920f1d1870a3689a1ce56010fbbe
      namespace: vote-app-dev
    name: uat
    referencePolicy:
      type: Source
