apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-push-pipeline
spec:
  params:
  - default: git commit -m "Update" . && git push origin master
    name: GIT_SCRIPT
    type: string
  tasks:
  - name: git-cli
    params:
    - name: BASE_IMAGE
      value: docker.io/alpine/git:v2.26.2@sha256:23618034b0be9205d9cc0846eb711b12ba4c9b468efdd8a59aac1d7b1a23363f
    - name: GIT_SCRIPT
      value: $(params.GIT_SCRIPT)
    - name: USER_HOME
      value: /tekton/home
    - name: VERBOSE
      value: "true"
    taskRef:
      kind: Task
      name: git-cli
    workspaces:
    - name: basic-auth
      workspace: basic-auth
    - name: source
      workspace: source
  workspaces:
  - name: basic-auth
  - name: source
