kind: Secret
apiVersion: v1
metadata:
  name: git-basic-auth-secret
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://repository-gitea.apps.cluster-s9tpk.s9tpk.sandbox222.opentlc.com"]
      helper = store
  .git-credentials: |
    https://demo:pw123!@repository-gitea.apps.cluster-s9tpk.s9tpk.sandbox222.opentlc.com
