apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    pipeline.openshift.io/started-by: opentlc-mgr
  labels:
    tekton.dev/pipeline: git-push-pipeline
  name: git-push-pipeline
spec:
  params:
  - name: GIT_SCRIPT
    value: |-
      pwd
      ls -a
      #git clone 
      git branch -v
      git remote -v
      #git checkout $(params.GIT_REVISION)
      #git pull origin roxctl-test
      git checkout roxctl-test || true
      #echo >> vote-app.yaml
      git status
      test -f vote-app.yaml && cp vote-app.yaml pipeline/acs/deploy/vote-app.yaml  # Hack
      ls 
      git add .
      git status
      git commit -m "Build update" .
      git status
      #git push origin $(params.GIT_REVISION)
      git push origin roxctl-test
      git status
#      echo >> Dockerfile
#      rm -rf * .??*
#      ls -a
#      git clone https://repository-gitea.apps.cluster-zt8j9.zt8j9.sandbox659.opentlc.com/demo/flask-vote-app.git .
#      cd flask-vote-app
#      git checkout roxctl-test
#      echo "# test change" >> Dockerfile
#      git commit -m "Test update to dockerfile" Dockerfile
#      git push origin roxctl-test
  pipelineRef:
    name: git-push-pipeline
  workspaces:
  - name: basic-auth
    secret:
      secretName: git-basic-auth-secret
  - name: source
    persistentVolumeClaim:
      claimName: pvc-85ae44d475

#  workspaces:
#    - name: workspace
#      volumeClaimTemplate:
#        metadata:
#          creationTimestamp: null
#          labels:
#            tekton.dev/pipeline: vote-app
#        spec:
#          accessModes:
#            - ReadWriteOnce
#          resources:
#            requests:
#              storage: 1Gi
