apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-app
    app.kubernetes.io/component: vote-app
    app.kubernetes.io/instance: vote-app
  name: vote-app
  namespace: vote-app-dev
spec:
  selector:
    matchLabels:
      deployment: vote-app
  template:
    metadata:
      labels:
        deployment: vote-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/vote-app-dev/vote-app@sha256:53187342e0acbf34c91b38765bdb8cf4180a19ba45fc2e56c4fcb2b8b1d8b31f
        name: vote-app
        ports:
        - containerPort: 8080
          protocol: TCP
