apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-app
    app.kubernetes.io/component: vote-app
    app.kubernetes.io/instance: vote-app
  name: vote-app
spec:
  selector:
    matchLabels:
      deployment: vote-app
  template:
    metadata:
      labels:
        deployment: vote-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/vote-app-dev/vote-app@sha256:7072a7969a0dd5bccd517dd6da06c5f446820277e6429a398cf493ee55d09c9d
        name: vote-app
        ports:
        - containerPort: 8080
          protocol: TCP
