apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-app
    app.kubernetes.io/component: vote-app
    app.kubernetes.io/instance: vote-app
  name: vote-app
  namespace: vote-app-dev
spec:
  selector:
    matchLabels:
      deployment: vote-app
  template:
    metadata:
      labels:
        deployment: vote-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/vote-app-dev/vote-app@sha256:9cc18daf90876a3d86fd19f92c90a8f561fe949faca66ccbd5235ec455a95898
        name: vote-app
        ports:
        - containerPort: 8080
          protocol: TCP
