apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vote-app
  namespace: vote-app-dev
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: vote-app@sha256:c6505ed61975ad588dc2fac30b66cce1cce699d51291eaa173096b03f836ee24
      namespace: vote-app-dev
    name: dev
    referencePolicy:
      type: Source
