apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-app3
  namespace: openshift-gitops
spec:
  destination:
    namespace: gitops-vote-app
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: deploy/gitops
    repoURL: https://github.com/sjbylo/flask-vote-app.git
    targetRevision: HEAD

